spring:
  application:
    name: flyway-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: tester
    password: lkr.7664
    locations: db/migration/V1_0_0,db/migration/V2_0_0