spring:
  application:
    name: flyway-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: tester
    password: balabala